name: Matrix Test Across OS

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        # Robot sẽ tạo ra 3 máy ảo khác nhau để chạy
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Test Bai 04
        # Lệnh này ép robot vào folder Bai04 để chạy test
        run: mvn -f Bai04/pom.xml test
